// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://souifygkwdqishngxmsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvdWlmeWdrd2RxaXNobmd4bXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTg5MzgsImV4cCI6MjA2NTU5NDkzOH0.8bl9ilTEOBKgzMQ29PXL2O92lfnuk2BBvrw2pWNqO6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);